export enum Symbols {
  // temporal placeholder until full symexec is implemented
  UNKNOWN = 'UNKNOWN',
  EMPTY = 'EMPTY',
  
  ADDRESS = 'ADDRESS',
  ORIGIN = 'ORIGIN',
  CALLER = 'CALLER',
  BALANCE = 'BALANCE',
  CALLVALUE = 'CALLVALUE',
  CALLDATASIZE = 'CALLDATASIZE',
  CALLDATALOAD = 'CALLDATALOAD',
  CODESIZE = 'CODESIZE',
  GAS = 'GAS',
  GASPRICE = 'GASPRICE',
  EXTCODESIZE = 'EXTCODESIZE'
}
